# Cloudflare Workers 配置文件
name = "vps-monitor-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
CORS_ORIGIN = "*"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "vps-monitor"
database_id = "6504b230-6a8f-4341-bbb6-599e915f48c1"

# KV 存储绑定 (用于缓存)
[[kv_namespaces]]
binding = "CACHE"
id = "f16627d17f134cddb15f46833d90d9a6"

# 定时任务配置 (暂时禁用)
# [[triggers.crons]]
# cron = "*/5 * * * *"  # 每5分钟检查离线服务器

# [[triggers.crons]]
# cron = "*/10 * * * *"  # 每10分钟运行连通性测试
